# _config.yml
title: Kodigo-Kid
description: Soluciones de arquitectura frente a problemas reales
theme: jekyll-theme-cayman   # o: jekyll-theme-minimal, jekyll-theme-slate, jekyll-theme-hacker
markdown: kramdown
